#\DeclareLyXModule{Newfangle Literate Listings}
#DescriptionBegin
#  Newfangle literate listings allow one to write
#   literate programs after the fashion of noweb, but without having
#   to use noweave to generate the documentation. Instead the listings
#   package is extended in conjunction with the noweb package to implement
#   to code formating directly as latex.
#  The newfangle awk script
#DescriptionEnd

Format 11

AddToPreamble
